[package]
name = "custom-deserialize"
version = "0.1.0"
authors = ["Kelly McLaughlin <kelly.mclaughlin@joyent.com>"]
edition = "2018"

[dependencies]

serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
uuid = { version = "0.5", features = ["serde", "v4"] }